package.json, src/apps/msafe-core/intention.ts, test/core.test.ts, yarn.lock
=> Fix sort key issue and add test

README.md
=> Add doc for app store

README.md
=> Add next step for README

src/apps/interface.ts, src/apps/mpay/cancel-stream.ts, src/apps/mpay/claim-by-proxy-stream.ts, src/apps/mpay/claim-stream.ts, src/apps/mpay/create-stream.ts, src/apps/mpay/decoder/create.ts, src/apps/mpay/helper.ts, src/apps/mpay/intention.ts, src/apps/mpay/set-auto-claim-stream.ts, src/apps/mpay/stream-intention.test.ts, src/apps/mpay/types/decode.ts
* Remove merge coins code
* Refactor MPay intention
* Add unit test
=> Refactor mpay

src/apps/navi/config.ts, src/apps/navi/decoder.ts, src/apps/navi/helper.ts, src/apps/navi/types.ts
implement deserialize function
=> navi: implement  deserialize

src/apps/cetus/helper.ts, src/apps/cetus/types.ts
=> fix: cetus implement deserialize

package.json, src/apps/turbos/helper.ts, src/apps/turbos/intentions/add-liquidity.ts, src/apps/turbos/intentions/burn.ts, src/apps/turbos/intentions/collect-fee.ts, src/apps/turbos/intentions/collect-reward.ts, src/apps/turbos/intentions/create-pool.ts, src/apps/turbos/intentions/decrease-liquidity.ts, src/apps/turbos/intentions/increase-liquidity.ts, src/apps/turbos/intentions/remove-liquidity.ts, src/apps/turbos/types.ts, yarn.lock
=> feat: turbos store

src/apps/navi/decoder.ts, src/apps/navi/intentions/claim-reward.ts, src/apps/navi/intentions/entry-borrow.ts, src/apps/navi/intentions/entry-deposit.ts, src/apps/navi/intentions/entry-repay.ts, src/apps/navi/intentions/entry-withdraw.ts, src/apps/navi/utils/token.ts
=> navi: fix claim reward

src/apps/turbos/decoder.ts
=> fix: get pool value

src/apps/turbos/decoder.ts
=> fix: get pool id object

src/apps/turbos/decoder.ts
=> refactor: get value string type

src/apps/cetus/helper.ts, src/apps/cetus/intention.ts
=> test: cetus test log

src/apps/navi/api/incentiveV2.ts, src/apps/navi/decoder.ts, src/apps/navi/intentions/claim-reward.ts
=> navi: fix claim rewards

package.json, src/apps/cetus/api/swap.ts, src/apps/cetus/config.ts, src/apps/cetus/helper.ts, src/apps/cetus/intentions/swap.ts, src/apps/cetus/types.ts, yarn.lock
=> feat: cetus swap

src/apps/turbos/decoder.ts
=> refactor: test

src/apps/turbos/decoder.ts
=> turbos: use decodeSharedObjectId

src/apps/turbos/decoder.ts
=> turbos: movecall 0x2::coin::zero

src/apps/turbos/decoder.ts
=> turbos: fix input index

test/cetus.test.ts
=> fix: cetus test update

package.json, src/apps/cetus/api/farming.ts, src/apps/cetus/api/position.ts, src/apps/cetus/api/swap.ts, src/apps/cetus/api/xcetus.ts, yarn.lock
=> fix: sui.js 0.50.1

src/apps/cetus/api/position.ts, src/apps/cetus/intentions/add-liquidity.ts, src/apps/cetus/intentions/claim-fee-and-mining.ts, src/apps/cetus/intentions/decrease-liquidity.ts, src/apps/cetus/intentions/farming-add.ts, src/apps/cetus/intentions/farming-batch-harvest.ts, src/apps/cetus/intentions/farming-claim-fee-and-rewards.ts, src/apps/cetus/intentions/farming-decrease.ts, src/apps/cetus/intentions/farming-harvest.ts, src/apps/cetus/intentions/farming-increase.ts, src/apps/cetus/intentions/farming-remove.ts, src/apps/cetus/intentions/farming-stake.ts, src/apps/cetus/intentions/farming-unstake.ts, src/apps/cetus/intentions/increase-liquidity.ts, src/apps/cetus/intentions/remove-liquidity.ts, src/apps/cetus/intentions/xcetus-cancel.ts, src/apps/cetus/intentions/xcetus-claim.ts, src/apps/cetus/intentions/xcetus-convert.ts, src/apps/cetus/intentions/xcetus-redeem-lock.ts, src/apps/cetus/intentions/xcetus-redeem.ts
=> test: add log

src/apps/cetus/helper.ts, src/apps/cetus/intentions/add-liquidity.ts, src/apps/cetus/intentions/claim-fee-and-mining.ts, src/apps/cetus/intentions/decrease-liquidity.ts, src/apps/cetus/intentions/farming-add.ts, src/apps/cetus/intentions/farming-batch-harvest.ts, src/apps/cetus/intentions/farming-claim-fee-and-rewards.ts, src/apps/cetus/intentions/farming-decrease.ts, src/apps/cetus/intentions/farming-harvest.ts, src/apps/cetus/intentions/farming-increase.ts, src/apps/cetus/intentions/farming-remove.ts, src/apps/cetus/intentions/farming-stake.ts, src/apps/cetus/intentions/farming-unstake.ts, src/apps/cetus/intentions/increase-liquidity.ts, src/apps/cetus/intentions/remove-liquidity.ts, src/apps/cetus/intentions/swap.ts, src/apps/cetus/intentions/xcetus-cancel.ts, src/apps/cetus/intentions/xcetus-claim.ts, src/apps/cetus/intentions/xcetus-convert.ts, src/apps/cetus/intentions/xcetus-redeem-lock.ts, src/apps/cetus/intentions/xcetus-redeem.ts
=> test: change log

src/apps/cetus/intentions/add-liquidity.ts, src/apps/cetus/intentions/claim-fee-and-mining.ts, src/apps/cetus/intentions/decrease-liquidity.ts, src/apps/cetus/intentions/farming-add.ts, src/apps/cetus/intentions/farming-batch-harvest.ts, src/apps/cetus/intentions/farming-claim-fee-and-rewards.ts, src/apps/cetus/intentions/farming-decrease.ts, src/apps/cetus/intentions/farming-harvest.ts, src/apps/cetus/intentions/farming-increase.ts, src/apps/cetus/intentions/farming-remove.ts, src/apps/cetus/intentions/farming-stake.ts, src/apps/cetus/intentions/farming-unstake.ts, src/apps/cetus/intentions/increase-liquidity.ts, src/apps/cetus/intentions/remove-liquidity.ts, src/apps/cetus/intentions/swap.ts, src/apps/cetus/intentions/xcetus-cancel.ts, src/apps/cetus/intentions/xcetus-claim.ts, src/apps/cetus/intentions/xcetus-convert.ts, src/apps/cetus/intentions/xcetus-redeem-lock.ts, src/apps/cetus/intentions/xcetus-redeem.ts
=> fix: intention txSubType

src/apps/cetus/api/farming.ts, src/apps/cetus/api/position.ts, src/apps/cetus/api/xcetus.ts
=> fix: api params fixs

src/apps/cetus/api/farming.ts, src/apps/cetus/intentions/farming-harvest.ts
=> fix: adjust farming harvest

src/apps/cetus/api/config.ts, src/apps/cetus/api/farming.ts, src/apps/cetus/api/position.ts, src/apps/cetus/api/swap.ts, src/apps/cetus/api/xcetus.ts, src/apps/cetus/helper.ts, src/apps/cetus/intentions/add-liquidity.ts, src/apps/cetus/intentions/claim-fee-and-mining.ts, src/apps/cetus/intentions/decrease-liquidity.ts, src/apps/cetus/intentions/farming-add.ts, src/apps/cetus/intentions/farming-batch-harvest.ts, src/apps/cetus/intentions/farming-claim-fee-and-rewards.ts, src/apps/cetus/intentions/farming-decrease.ts, src/apps/cetus/intentions/farming-harvest.ts, src/apps/cetus/intentions/farming-increase.ts, src/apps/cetus/intentions/farming-remove.ts, src/apps/cetus/intentions/farming-stake.ts, src/apps/cetus/intentions/farming-unstake.ts, src/apps/cetus/intentions/increase-liquidity.ts, src/apps/cetus/intentions/remove-liquidity.ts, src/apps/cetus/intentions/swap.ts, src/apps/cetus/intentions/xcetus-cancel.ts, src/apps/cetus/intentions/xcetus-claim.ts, src/apps/cetus/intentions/xcetus-convert.ts, src/apps/cetus/intentions/xcetus-redeem-lock.ts, src/apps/cetus/intentions/xcetus-redeem.ts
=> fix: add testnet

src/apps/turbos/decoder.ts
=> turbos: decode deadline

package.json, src/apps/scallop/builders/borrowIncentiveBuilder.ts, src/apps/scallop/config.ts, src/apps/scallop/intentions/claim-incentive-reward.ts, src/apps/scallop/models/scallopClient.ts, src/apps/scallop/types/builder/borrowIncentive.ts, src/apps/scallop/types/builder/spool.ts
=> feat: update borrow incentive

src/apps/kriya/config.ts, src/apps/kriya/decoder.ts, src/apps/kriya/helper.ts, src/apps/kriya/intentions/add-liquidity.ts, src/apps/kriya/intentions/add-liquiditySingleSided.ts, src/apps/kriya/intentions/claim-rewards.ts, src/apps/kriya/intentions/remove-liquidity.ts, src/apps/kriya/intentions/stake-liquidity.ts, src/apps/kriya/intentions/unstake-liquidity.ts, src/apps/kriya/types.ts, test/kriya.test.ts
=> Integrated kriya dApp with Msafe

src/apps/turbos/decoder.ts, src/apps/turbos/helper.ts
=> turbos: cache params

package.json, src/apps/scallop/builders/oracle.ts, src/apps/scallop/models/pythClient.ts, test/scallop.test.ts
=> feat: add pyth client

src/apps/turbos/decoder.ts, src/apps/turbos/helper.ts
=> turbos: remove liquidity and swap

src/apps/volo/config.ts, src/apps/volo/decoder.ts, src/apps/volo/helper.ts, src/apps/volo/intentions/claimTicket.ts, src/apps/volo/intentions/stake.ts, src/apps/volo/intentions/unStake.ts, src/apps/volo/types.ts
support volo stake, unstake, burn_ticket
=> volo integrate

src/apps/kriya/intentions/add-liquidity.ts, src/apps/kriya/intentions/add-liquiditySingleSided.ts, src/apps/kriya/intentions/claim-rewards.ts, src/apps/kriya/intentions/remove-liquidity.ts, src/apps/kriya/intentions/stake-liquidity.ts, src/apps/kriya/intentions/unstake-liquidity.ts
=> Update kriya spot sdk import

src/apps/scallop/decoder.ts, src/apps/scallop/helper.ts, src/apps/scallop/intentions/borrow-with-boost.ts, src/apps/scallop/intentions/deposit-collateral.ts, src/apps/scallop/intentions/migrate-and-claim.ts, src/apps/scallop/intentions/redeem-sca.ts, src/apps/scallop/intentions/stake-sca.ts, src/apps/scallop/models/scallopClient.ts, src/apps/scallop/types/utils.ts, src/apps/scallop/utils/builder.ts, src/index.ts, test/scallop.test.ts
=> Add intention and fix bug

src/apps/turbos/decoder.ts, src/apps/turbos/helper.ts, src/apps/turbos/intentions/remove-liquidity.ts
=> turbos: get decrease liquidity helper

src/apps/turbos/decoder.ts, src/apps/turbos/helper.ts
=> turbos: fix swap nexttick

src/apps/turbos/decoder.ts
=> fix: new bn

src/apps/turbos/decoder.ts, src/apps/turbos/helper.ts, src/apps/turbos/intentions/claim-all.ts, src/apps/turbos/types.ts
=> turbos: remove log

src/apps/scallop/decoder.ts, src/apps/scallop/intentions/extend-period-and-stake-more.ts, src/apps/scallop/intentions/extend-stake-period.ts, test/scallop.test.ts
=> Fix SCA staking and incentive claim reward

package.json, src/apps/kriya/config.ts, src/apps/kriya/decoder.ts, src/apps/kriya/helper.ts, src/apps/kriya/intentions/add-liquidity.ts, src/apps/kriya/intentions/add-liquiditySingleSided.ts, src/apps/kriya/intentions/claim-rewards.ts, src/apps/kriya/intentions/remove-liquidity.ts, src/apps/kriya/intentions/stake-liquidity.ts, src/apps/kriya/intentions/unstake-liquidity.ts, src/apps/kriya/types.ts, test/kriya.test.ts, yarn.lock
=> msafe integration kriya

package.json, src/apps/kriya/intentions/add-liquidity.ts, src/apps/kriya/intentions/add-liquiditySingleSided.ts, src/apps/kriya/intentions/claim-rewards.ts, src/apps/kriya/intentions/remove-liquidity.ts, src/apps/kriya/intentions/stake-liquidity.ts, src/apps/kriya/intentions/unstake-liquidity.ts, yarn.lock
=> update sdk packages and modification

.gitignore, src/apps/turbos/decoder.ts
=> turbos: slippage 10

src/apps/turbos/decoder.ts
=> turbos:fix decode swap

src/apps/turbos/config.ts
=> turbos: remove

src/apps/kriya/intentions/stake-liquidity.ts
=> resolved conflicts with main update

src/apps/turbos/api/deepbook.ts, src/apps/turbos/config.ts, src/apps/turbos/decoder.ts, src/apps/turbos/helper.ts, src/apps/turbos/intentions/swap-exact-base-for-quote.ts, src/apps/turbos/intentions/swap-exact-quote-for-base.ts, src/apps/turbos/types.ts, src/apps/turbos/utils/sui-kit.ts
=> turbos: use sdk contract

src/apps/turbos/decoder.ts
=> turbos: fix typearg

src/apps/turbos/decoder.ts
=> turbos: use short address

src/apps/turbos/intentions/swap-exact-base-for-quote.ts, src/apps/turbos/intentions/swap-exact-quote-for-base.ts, src/apps/turbos/types.ts
=> turbos: fix txsubtype

package.json, src/apps/kriya/decoder.ts, src/index.ts, test/kriya.test.ts, yarn.lock
Upgraded our sdk to be compatible with mysten/bcs library, and edited our kriya test file to pass all serialization case.
=> Kriya New Version upgrade

src/apps/turbos/helper.ts, src/apps/turbos/intentions/swap.ts
=> turbos: chore log

src/apps/cetus/api/vesting.ts, src/apps/cetus/helper.ts, src/apps/cetus/intentions/vesting-redeem.ts, src/apps/cetus/types.ts
=> feat: add vesting redeem

src/apps/navi/decoder.ts, src/apps/navi/helper.ts, src/apps/navi/intentions/multi-deposit.ts, src/apps/navi/types.ts
[navi] support multi deposit operation.
=> navi: support one-click supply

package.json, src/apps/bluefin/config.ts, src/apps/bluefin/helper.ts, src/apps/bluefin/intentions/close-position.ts, src/apps/bluefin/intentions/collect-fee-and-rewards.ts, src/apps/bluefin/intentions/collect-fee.ts, src/apps/bluefin/intentions/collect-rewards.ts, src/apps/bluefin/intentions/open-position-with-liquidity.ts, src/apps/bluefin/intentions/provide-liquidity.ts, src/apps/bluefin/intentions/remove-liquidity.ts, src/apps/bluefin/tx-builder.ts, src/apps/bluefin/types.ts, src/index.ts, test/bluefin.test.ts, yarn.lock
=> Bluefin Integration

package.json, src/apps/alphafi/decoder.ts, src/apps/alphafi/helper.ts
Added Decoder logic to Alphafi app and updated the same in its helper file.
Also updated alphafi-sdk version.
=> feat: adding decoder logic to alphafi

package.json, src/apps/cetus/api/config.ts, src/apps/cetus/api/vaults.ts, src/apps/cetus/helper.ts, src/apps/cetus/intentions/vaults-add.ts, src/apps/cetus/intentions/vaults-remove.ts, src/apps/cetus/types.ts, yarn.lock
=> feat: add vaults

src/apps/bluefin/decoder.ts, src/apps/bluefin/helper.ts, src/apps/bluefin/intentions/close-position.ts, src/apps/bluefin/intentions/collect-fee-and-rewards.ts, src/apps/bluefin/intentions/collect-fee.ts, src/apps/bluefin/intentions/collect-rewards.ts, src/apps/bluefin/intentions/open-position-with-liquidity.ts, src/apps/bluefin/intentions/provide-liquidity.ts, src/apps/bluefin/intentions/remove-liquidity.ts, src/apps/bluefin/tx-builder.ts, test/bluefin.test.ts
- Moved `OpenPositionAndAddLiquidity` to Legacy
- Commented out all other intentions for now, will have them updated to legacy once we have tested the open position and add liquidity to work e2e.
=> Bluefin - Moved Open Position And Add Liquidity to Legacy Sui

package.json, src/apps/registry.ts, src/lib/MSafeHTTPTransport/errors.ts, src/lib/MSafeHTTPTransport/index.ts, src/lib/MSafeHTTPTransport/rpc-websocket-client.ts, yarn.lock
feat: add custom http transport
=> feat: add custom http transport

src/apps/bluefin/decoder.ts
- Logging commands and inputs received by `decoder` for debugging purposes.
- Removed disable prettier from bluefin decoder
=> Bluefin - Log commands and inputs

test/bluefin.test.ts
=> Bluefin - Fix Failing test

src/apps/bluefin/decoder.ts, src/apps/bluefin/intentions/close-position.ts, src/apps/bluefin/intentions/collect-fee-and-rewards.ts, src/apps/bluefin/intentions/collect-fee.ts, src/apps/bluefin/intentions/collect-rewards.ts, src/apps/bluefin/intentions/open-position-with-liquidity.ts, src/apps/bluefin/intentions/provide-liquidity.ts, src/apps/bluefin/intentions/remove-liquidity.ts, src/apps/bluefin/tx-builder.ts, src/apps/bluefin/types.ts, src/apps/turbos/types.ts, test/bluefin.test.ts
- Removed `action` from `BluefinIntionData` - Now the intention only contains transaction parameters.
- Added intention data types for all intentions
- Added a deserialize and build test
=> Bluefin - Misc Updates

package.json, src/apps/alphafi/decoder.ts, src/apps/alphafi/helper.ts, src/apps/alphafi/intentions/deposit-double-asset.ts, src/apps/alphafi/intentions/deposit-single-asset.ts, src/apps/alphafi/intentions/withdraw-alpha.ts, src/apps/alphafi/intentions/withdraw.ts, yarn.lock
Added debugging console logs updated @alphafi/alphafi-sdk version.
=> feat: adding debug logs and updated @alphafi/alphafi-sdk version

package.json, src/apps/bluefin/decoder.ts, src/apps/bluefin/helper.ts, src/apps/bluefin/intentions/collect-rewards-and-fee.ts, src/apps/bluefin/intentions/open-position-with-liquidity.ts, src/apps/bluefin/tx-builder.ts, src/apps/bluefin/types.ts, test/bluefin.test.ts, yarn.lock
Added the following intentions:
- Close Position
- Provide Liquidity
- Remove Liquidity
- Collect Fee
- Collect Rewards
- Collect Rewards and Fee
Updated `bluefin.test.ts` with new tests for all intentions.
=> Bluefin - Added Intentions

src/apps/alphafi/decoder.ts, test/alphafi.test.ts
=> feat: AlphaFi decoder fix and test updation

src/apps/alphafi/decoder.ts
=> feat: Updating decoder for AlphaFi

src/apps/registry.ts, src/apps/scallop/types/utils.ts, src/apps/turbos/types.ts, test/core.test.ts
1. Added a check for the account's SUI balance before helper.build. If the balance is less than 0.1 SUI, an exception is thrown.
2. Added test cases for the above scenario.
=> feat: add sui balance check

src/apps/alphafi/decoder.ts, test/alphafi.test.ts
Added some more tests and updated the extractXTokensAmount function for alphafi
=> feat: Alphafi bug fix and test addition

package.json, src/apps/alphafi/decoder.ts, yarn.lock
fixed a small bug in alphafi decoder for single asset deposits and updated alphafi-sdk package
=> feat: Alphafi bug fix decode Single Asset Deposit and package upgrade

src/apps/alphafi/decoder.ts, test/alphafi.test.ts
=> feat: Alphafi tests update

package.json, src/apps/stsui/decoder.ts, src/apps/stsui/helper.ts, src/apps/stsui/intentions/mint.ts, src/apps/stsui/intentions/redeem.ts, src/apps/stsui/types.ts, test/stsui.test.ts, yarn.lock
Added all code related to stsui integration. Also wrote tests for it.
Had to upgrade @alphafi/alphafi-sdk version due to some version dependency error in @mysten/sui.
=> Stsui Integration

src/apps/scallop/constants/common.ts, src/apps/scallop/constants/enum.ts, src/apps/scallop/intentions/lending/migrate-wusd-to-usdc.ts, src/apps/scallop/intentions/lending/supply-lending.ts, src/apps/scallop/intentions/lending/withdraw-and-unstake-lending.ts, src/apps/scallop/intentions/lending/withdraw-lending.ts, src/apps/scallop/intentions/staking/supply-and-stake-lending.ts, src/apps/scallop/models/index.ts, src/apps/scallop/models/scallop.ts, src/apps/scallop/models/scallopClient.ts, src/apps/scallop/queries/borrowIncentiveQuery.ts
- Fix the issue of contract mismatch due to the updated contract.
- Add support for isolated asset pools and update the new pool.
=> Scallop: fix contract version mismatch and support isolated asset

src/apps/scallop/utils/util.ts
=> fix: build issue

src/apps/bluefin/config.ts
Updated the current supported package address of Bluefin Spot
=> Bluefin Contract Update

package.json, yarn.lock
upgrading @alphafi/alphafi-sdk and @alphafi/stsui-sdk version
=> feat: upgrading @alphafi/alphafi-sdk and @alphafi/stsui-sdk version

.vscode/settings.json, package.json, src/apps/springSui/intentions/convert.ts, src/apps/springSui/intentions/convertAndDeposit.ts, src/apps/springSui/intentions/stake.ts, src/apps/springSui/intentions/stakeAndDeposit.ts, src/apps/springSui/intentions/unstake.ts, src/apps/suilend/constants.ts, src/apps/suilend/decoder.ts, src/apps/suilend/helper.ts, src/apps/suilend/intentions/borrow.ts, src/apps/suilend/intentions/claim.ts, src/apps/suilend/intentions/claimAndDeposit.ts, src/apps/suilend/intentions/deposit.ts, src/apps/suilend/intentions/repay.ts, src/apps/suilend/intentions/withdraw.ts, src/apps/suilend/utils/getRewards.ts, yarn.lock
* Update Suilend and SpringSui @suilend dependencies.
=> Suilend/Springsui - update @suilend deps

package.json, yarn.lock
- Moves `@suilend/frontend-sui`, `@suilend/sdk`, and `@suilend/springsui-sdk` from `peerDependencies` to `dependencies`
=> reorganize @suilend dependencies

package.json, yarn.lock
=> kriya-dev-sdk upgrade

src/apps/navi/intentions/multi-deposit.ts
=> navi: fix multi deposit

package.json, yarn.lock
- Use deprecated @mysten/bcs functions in Suilend SDK
=> Suilend SDK: Use useHEX instead of useHex

package.json, src/apps/cetus/api/config.ts, yarn.lock
cetus aggregator and vaults sdk upgrade
=> fix: cetus aggregator and vaults sdk upgrade

src/apps/cetus/api/config.ts, test/bucket.test.ts
- fixed `peripheryConfig` (please confirm setting)
- fixed test `lock-claim`
Hope you find this helpful!
@msafe-admin @0xshiba1
=> fix: failing tests fixed

src/apps/plain-transaction/helper.ts
=> feat: add logging for account in PlainTransactionHelper

src/apps/plain-transaction/helper.ts
=> fix: remove console log for account in PlainTransactionHelper

.gitignore, .vscode/settings.json, package.json, src/apps/mmt-dex/helper.ts, src/apps/mmt-dex/intentions/stake-xsui.ts, src/apps/mmt-dex/intentions/unstake-xsui.ts, src/apps/mmt-dex/types.ts, src/apps/mmt-dex/utils/stake.ts
=> feat: add staking adaptor

package.json, yarn.lock
=> fix: cetus sdk upgrade

src/apps/turbos/decoder.ts
=> fix: turbos share objectid

package.json, src/apps/bluefin/decoder.ts, src/apps/bluefin/helper.ts, src/apps/bluefin/intentions/aggregator-7k-swap.ts, src/apps/bluefin/tx-builder.ts, src/apps/bluefin/types.ts, yarn.lock
Adding functionality to execute a 7K aggregator swap on Blueifn UI using Msafe wallet
TODO: 
- Remove hardcoded input amount and slippage values in future PR.
=> Bluefin - 7K Aggregator Swaps

src/apps/bluefin/decoder.ts, src/apps/bluefin/helper.ts, src/apps/bluefin/tx-builder.ts, src/apps/bluefin/types.ts
Updated the deserialize method and decoder to accept the appContext for incoming Tx and use that to extract the tx params for 7K aggregator swap call.
=> Bluefin - 7K Aggrgator - App Context

package.json, src/apps/scallop/intentions/staking/redeem-sca.ts, src/apps/scallop/intentions/staking/withdraw-staked-sca.ts, src/apps/springSui/intentions/convert.ts, src/apps/springSui/intentions/convertAndDeposit.ts, src/apps/springSui/intentions/unstake.ts, yarn.lock
- Updated @babel/core and @jridgewell/sourcemap-codec versions in yarn.lock
- Refactored transaction methods in staking and conversion intentions to use new parameters
- Updated import statements for LstClient and conversion functions in convert.ts and convertAndDeposit.ts
=> feat: update dependencies and refactor transaction methods
